#cloud-config

# include one or more SSH public keys
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCTzen3Ers3S6aJtZRWC5nAEd2lfTinkCrSy8IYYmr0MkTgcdgjU8hUzPoSZ4uhN98OffYryGUGuax0Q8Yo3DaUY/CRokB0fnD7H2kkK+Wl0TNIoeZjBo8MSRgh/lfEpeqxtPC9w6t457juFZRl5Jfv5G1aKBC7AQLymaUVX2ACofQ5W1HhdH3AINATFo8xx+NZS3BSgPdQ0LhMPjoxDuN90YVP9BHadkMCOJZaidvLwves/nDKOJKpIbIcP7xMAZXf0mCcDK/jOR8RxEnx1D6p8qFfYDgI6K56QygTZhzlZQKSxoK4atrS+YgVuIkN71X4mmIDz+soZw3MQxNmTTH maanadev@maanadev-ThinkPad-T520

coreos:
  etcd2:
    name: "coreos-cluster-etcd2-01"
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    advertise-client-urls: http://192.168.19.218:2379
    initial-advertise-peer-urls: http://192.168.19.218:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://192.168.19.218:2380,http://192.168.19.218:7001
    initial-cluster: coreos-cluster-etcd2-01=http://192.168.19.218:2380,coreos-cluster-etcd2-02=http://192.168.19.249:2380,coreos-cluster-etcd2-03=http://192.168.19.251:2380
    initial-cluster-state: new 
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: systemd-networkd.service
      command: stop
    - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=enp0s25

        [Network]
        Address=192.168.19.218/22
        Gateway=192.168.16.254
        DNS=192.168.8.3
    - name: down-interfaces.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/ip link set enp0s25 down
        ExecStart=/usr/bin/ip addr flush dev enp0s25
    - name: systemd-networkd.service
      command: restart 

users:
  - name: "appcloud"
    passwd: "$6$rounds=4096$q0YignYXGTo$liAY7m9FjnH4l0wghUoCW19wA9xtb9FIHuM81l.SfHKSp8UFnvOu/a.pHkVlVO4EbWugfyWy1DHgKNzpiCnZe/"
    groups:
      - "sudo"
      - "docker"
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCTzen3Ers3S6aJtZRWC5nAEd2lfTinkCrSy8IYYmr0MkTgcdgjU8hUzPoSZ4uhN98OffYryGUGuax0Q8Yo3DaUY/CRokB0fnD7H2kkK+Wl0TNIoeZjBo8MSRgh/lfEpeqxtPC9w6t457juFZRl5Jfv5G1aKBC7AQLymaUVX2ACofQ5W1HhdH3AINATFo8xx+NZS3BSgPdQ0LhMPjoxDuN90YVP9BHadkMCOJZaidvLwves/nDKOJKpIbIcP7xMAZXf0mCcDK/jOR8RxEnx1D6p8qFfYDgI6K56QygTZhzlZQKSxoK4atrS+YgVuIkN71X4mmIDz+soZw3MQxNmTTH maanadev@maanadev-ThinkPad-T520

hostname: "coreos-cluster-01"
